import { query, mutation, action } from "../_generated/server";
import { v } from "convex/values";
import { api } from "../_generated/api";

export const list = query({
    args: {},
    handler: async (ctx) => {
        return await ctx.db
            .query("articles")
            .withIndex("by_published", (q) => q.eq("is_published", true))
            .order("desc")
            .collect();
    },
});

export const getBySlug = query({
    args: { slug: v.string() },
    handler: async (ctx, args) => {
        return await ctx.db
            .query("articles")
            .withIndex("by_slug", (q) => q.eq("slug", args.slug))
            .first();
    },
});

// The "Agent" Action
export const generate = action({
    args: { topic: v.string(), count: v.number() },
    handler: async (ctx, args) => {
        // This is where we would call OpenAI/Anthropic to generate content.
        // For the demo, we will generate "Agent Created" content programmatically.

        const newArticles = [];
        for (let i = 0; i < args.count; i++) {
            const title = `${args.topic} - Part ${i + 1}`;
            newArticles.push({
                title: title,
                slug: `${args.topic.toLowerCase().replace(/\s+/g, '-')}-${i + 1}-${Date.now()}`,
                excerpt: `AI-Generated insight about ${args.topic}. Fresh content brought to you by your automated agent.`,
                content: `
# The Future of ${args.topic}

As we look towards the horizon, the intersection of technology and open-air driving continues to evolve. 
This article was generated by your intelligent agent to expand your content library automatically.

## Key Points
- Innovation is constant.
- The Slingshot experience remains unique.
- Utah's landscape offers endless possibilities.

(This is a placeholder for LLM-generated text. Connect an API Key to generate real paragraphs).
            `,
                image_url: "/hero.png", // Fallback or generate new one via DALL-E API
                author: "AI Content Agent",
                is_published: true,
                published_at: Date.now(),
            });
        }

        // Insert them via mutation
        await ctx.runMutation(api.articles.insertBatch, { articles: newArticles });
        return { success: true, count: args.count };
    },
});

export const insertBatch = mutation({
    args: { articles: v.any() },
    handler: async (ctx, args) => {
        for (const article of args.articles) {
            await ctx.db.insert("articles", article);
        }
    }
});

export const seed = mutation({
    args: {},
    handler: async (ctx) => {
        // Clear existing for a clean "re-seed" (Optional, but good for dev)
        const existing = await ctx.db.query("articles").collect();
        for (const doc of existing) {
            await ctx.db.delete(doc._id);
        }

        const articles = [
            {
                title: "Top 5 Scenic Drives in Northern Utah",
                slug: "top-5-scenic-drives-utah",
                excerpt: "Discover the most breathtaking routes to take your Slingshot on this weekend. From the Alpine Loop to Logan Canyon, these drives redefine 'scenic'.",
                content: `
# The Call of the Canyon

Utah is home to some of the most spectacular driving roads in the country, and there is no better way to experience them than in an open-cockpit Polaris Slingshot. The visceral connection to the road, the wind in your face, and the panoramic views create a sensory experience that a standard car simply cannot match.

## 1. The Alpine Loop (Provo Canyon to American Fork Canyon)
This 20-mile scenic byway is a rite of passage for any Utah driver. As you climb past soaring limestone cliffs and through dense aspen groves, the nimble handling of the Slingshot shines. The tight switchbacks near the summit offer a thrilling test of the vehicle's cornering capabilities. **Pro Tip:** Stop at Sundance Resort for a high-end brunch.

## 2. Logan Canyon National Scenic Byway
Heading north? Logan Canyon offers 41 miles of winding excellence. The road follows the Logan River, providing a cool, refreshing mist on hot summer days. The limestone rock formations tower above you, creating a dramatic corridor that feels almost prehistoric.

## 3. Mirror Lake Highway
Climbing into the Uintas, this is one of the highest paved roads in the state. The air is crisp, the views are expansive, and the tarmac is smooth. It's a longer cruise, perfect for a full-day rental.

## 4. Big Cottonwood Canyon
Famous for its ski resorts, in the summer, this canyon is a driver's paradise. The S-curves are rhythmic and satisfying. Just be mindful of cyclists and hikers sharing the road.

## 5. Nebo Loop
For those willing to venture a bit further south towards Payson, the Nebo Loop offers solitude and grand vistas of Utah Valley and Mount Nebo. The road is narrower, demanding focus, but the payoff is an uninterrupted flow state.
        `,
                image_url: "/article_scenic_drive.png",
                author: "Doorman Ria",
                is_published: true,
                published_at: Date.now(),
            },
            {
                title: "Why Reviewers Love the Polaris Slingshot R",
                slug: "polaris-slingshot-r-review",
                excerpt: "An in-depth look at the performance, style, and features of the Slingshot R. Is it a car? Is it a motorcycle? It's pure adrenaline.",
                content: `
# The Beast Unleashed

The Polaris Slingshot R is the ultimate statement vehicle. It sits at the top of the lineup, boasting the most aggressive styling, the most powerful engine tune, and premium finishes that turn heads at every intersection.

## Performance Specs
Under the hood lies the ProStar 2.0L 4-cylinder engine, delivering **203 horsepower**. In a vehicle that weighs under 1,700 lbs, that power-to-weight ratio is startling. 0-60 mph comes up in just 4.9 seconds. But stats don't tell the whole story. It's the *delivery* of power that hooks you. The engine screams to 8,500 RPM, a mechanical symphony that encourages you to push harder.

## Handling and Dynamics
Reviewers consistently praise the direct steering rack. There is zero play. You think about turning, and the car... excuse me, the *autocycle*... reacts instantly. The wide front track and massive rear tire verify that you have immense mechanical grip.

## The Verdict
"It's not about practicality," says *Car & Driver*. "It's about the joy of driving in its purest form." We couldn't agree more. The Slingshot R isn't for grocery runs; it's for soul-cleansing blasts down your favorite backroad.
        `,
                image_url: "/article_slingshot_review.png",
                author: "Auto Expert",
                is_published: true,
                published_at: Date.now() - 86400000,
            },
            {
                title: "Night Rides: Cruising Provo in Style",
                slug: "night-rides-provo",
                excerpt: "The city lights look different from an open cockpit. Here is our guide to night riding, best routes for neon vibes, and late-night eats.",
                content: `
# Own the Night

There is nothing quite like the cool night air hitting your face as you cruise down Center Street. The Slingshot's interior ambient lighting glows, matching the neon signs of the city. You aren't just observing the nightlife; you are *part* of it.

## The Downtown Loop
Start your evening on Center Street in Provo. The historic architecture mixed with modern dining creates a vibrant backdrop. The slow cruise allows you to soak in the atmosphere (and let's be honest, show off the ride).

## Up to the 'Y'
Drive up to the Y Trailhead parking lot. The view of the valley lights sparkling below is romantic and serene. It's the perfect spot to park, listen to some music on the premium Rockford Fosgate audio system, and just talk.

## Safety at Night
Our fleet comes equipped with high-intensity LED headlights that cut through the darkness, ensuring you see and *are seen*. We always recommend a light jacket for night rides, even in summer, as the open-air cabin can get breezy.
         `,
                image_url: "/article_night_ride.png",
                author: "Doorman Ria",
                is_published: true,
                published_at: Date.now() - 172800000,
            },
            {
                title: "Safety First: Helmet Laws and Slingshots",
                slug: "safety-helmet-laws",
                excerpt: "Everything you need to know about staying safe and legal on the road. Do you need a helmet? What about a motorcycle license?",
                content: `
# Know Before You Go

One of the most common questions we get is: "Do I need a helmet?" The answer depends on your age and local laws, but at **SlingMe**, we prioritize your safety above all else.

## The Legal Stance
In Utah, the Slingshot is classified as an **Autocycle**. This is a specific category distinct from motorcycles.
- **Motorcycle Endorsement:** You **DO NOT** need a motorcycle endorsement to drive a Slingshot in Utah. A standard driver's license is sufficient.
- **Helmets:** Utah law requires helmets for riders and passengers under the age of 21. For those 21 and over, it is optional but *highly recommended*.

## Why We Recommend Helmets
Even with a roll hoop and seatbelts, you are exposed to the elements. A rock kicked up by a truck, a large insect, or wind noise can be fatiguing. A full-face helmet provides:
1.  **Eye Protection:** Crucial at highway speeds.
2.  **Noise Reduction:** Makes the ride more comfortable.
3.  **Impact Protection:** In the unlikely event of an accident.

We provide sanitized, high-quality helmets with every rental for those who want them.
          `,
                image_url: "/article_safety_helmet.png",
                author: "Safety Team",
                is_published: true,
                published_at: Date.now() - 259200000,
            },
            {
                title: "Manual vs Auto: Which Slingshot is for You?",
                slug: "manual-vs-auto",
                excerpt: "Breaking down the driving experience of the AutoDrive vs traditional stick shift. Which transmission suits your driving style?",
                content: `
# The Great Transmission Debate

Originally, the Polaris Slingshot was manual only. It was a machine for purists. But with the introduction of the **AutoDrive** transmission, the experience opened up to everyone. So, which should you choose?

## The Manual (5-Speed)
**For the Driver:** If you know how to heel-toe downshift, if you love finding the perfect bite point of a clutch, the manual is for you. It's a short-throw gearbox that feels mechanical and precise. You are in total control of the engine's power band.
*   **Pros:** Engaging, traditional sportscar feel.
*   **Cons:** Traffic can be a chore.

## The AutoDrive (Paddle Shifters)
**For the Cruiser:** The AutoDrive is an automated manual transmission. It shifts for you, but you can take control with steering-wheel-mounted paddle shifters. It's smooth, accessible, and lets you focus on the scenery rather than the tachometer.
*   **Pros:** Easy to drive, anyone can rent it, paddle shifting is fun.
*   **Cons:** Slightly less connection to the drivetrain.

## Our Recommendation
If you are renting for a technical canyon run and know how to drive stick, go Manual. If you are cruising Main Street or heading out for a date night, the AutoDrive offers a more relaxed, luxury experience.
          `,
                image_url: "/article_manual_shifter.png",
                author: "Gearhead",
                is_published: true,
                published_at: Date.now() - 345600000,
            },
            {
                title: "The Ultimate Date Night Idea",
                slug: "ultimate-date-night",
                excerpt: "Forget dinner and a movie. Rent a Slingshot for an unforgettable evening. Here is the perfect itinerary for romance.",
                content: `
# Impress Your Date

Let's face it: dinner and a movie is safe. It's predictable. But you didn't come to **SlingMe** for predictable. You came for unforgettable. Renting a Slingshot for date night signals that you are adventurous, spontaneous, and appreciate style.

## The Itinerary
1.  **5:00 PM - Pickup:** Arrive at our location. The car is detailed, fueled, and waiting. As you slide into the cockpit, the tone is set.
2.  **6:00 PM - Scenic Drive:** Head up the Alpine Loop just as the sun begins to dip. The golden hour light hitting the red bodywork of the Slingshot makes for incredible photos (and selfies).
3.  **7:30 PM - Dinner:** Valet park at a high-end restaurant like The Tree Room or a trendy spot in downtown Provo. The valet *will* park it out front. It's that kind of car.
4.  **9:00 PM - The Cruise:** Top down (well, there is no top), music up, cruising home under the stars.

## Why It Works
Shared adrenaline releases dopamine and oxytocin—the bonding chemicals. Trying something new together strengthens relationships. Plus, the cozy cockpit means you are sitting shoulder-to-shoulder the whole time.
          `,
                image_url: "/article_date_night.png",
                author: "Lifestyle Editor",
                is_published: true,
                published_at: Date.now() - 432000000,
            },
            {
                title: "Slingshot vs Convertible: What is the Difference?",
                slug: "slingshot-vs-convertible",
                excerpt: "Comparing the open-air experience of a traditional convertible vs a 3-wheeler. Why the Slingshot hits different.",
                content: `
# Redefining Open Air

You might think, "I've driven a convertible Mustang, I know what this is like." Respectfully, you don't. A traditional convertible isolates you. You sit *in* it, surrounded by high doors, sound deadening, and a heavy chassis.

## The Cockpit Feel
In a Slingshot, you don't sit in it; you strap *on* to it. You are inches from the ground. The half-doors (or lack thereof) mean you can see the pavement rushing by. You feel every texture of the road.

## The Attention Factor
Drive a convertible BMW, and no one looks. Drive a Slingshot, and everyone looks. Kids wave, people pull out phones, other drivers give thumbs up. It's a celebrity experience.

## The Agility
With only three wheels and a lightweight frame, the Slingshot changes direction like a dragonfly. It's twitchy, responsive, and alive. A standard convertible feels like a boat in comparison. 
          `,
                image_url: "/article_convertible_comparison.png",
                author: "Car Geek",
                is_published: true,
                published_at: Date.now() - 518400000,
            },
            {
                title: "Fall Foliage Tours in the Wasatch Range",
                slug: "fall-foliage-tours",
                excerpt: "Best times and places to see the autumn colors from the cockpit. Why an open root is the best way to leaf peep.",
                content: `
# A Palette of Gold and Crimsom

Mid-September to early October is a magical time in Northern Utah. The aspen groves transform into shimmering rivers of gold, and the maples turn a deep, fiery crimson. Viewing this from behind glass is fine. Viewing it with 360-degree unobstructed views is spiritual.

## Best Leaf Peeping Routes
1.  **Guardsman Pass:** Connecting Park City to Big Cottonwood. The colors here are intense.
2.  **East Canyon:** A quieter route with rolling hills of color.
3.  **Monte Cristo:** Further north near Ogden, known for its sprawling aspen forests.

## Photography Tips
Park the Slingshot against a backdrop of yellow aspens. The contrast of the sharp, angular, red machine against the organic, soft yellow leaves creates a stunning image.
          `,
                image_url: "/article_fall_foliage.png",
                author: "Nature Lover",
                is_published: true,
                published_at: Date.now() - 604800000,
            },
            {
                title: "Group Rides: Renting Multiple Vehicles",
                slug: "group-rides",
                excerpt: "Planning a bachelor party or corporate event? Here is how to book our fleet for a convoy experience.",
                content: `
# The Wolfpack

Riding solo is therapeutic. Riding in a pack is an event. We offer fleet rentals for groups looking to make a massive impact. 

## Perfect For:
-   **Bachelor/Bachelorette Parties:** Skip the limo. Drive yourselves.
-   **Corporate Retreats:** Team building that people actually want to do.
-   **Family Reunions:** The "cool uncle" move.

## Logistics
When driving in a group of Slingshots, we recommend a staggered formation (safety first!). Our team can help program the GPS units on all vehicles to follow the same route, ensuring no one gets lost. We can also arrange for a support vehicle if needed for larger groups.
          `,
                image_url: "/article_group_ride.png",
                author: "Events Coordinator",
                is_published: true,
                published_at: Date.now() - 691200000,
            },
            {
                title: "Maintenance 101: How We Keep Our Fleet Pristine",
                slug: "maintenance-101",
                excerpt: "A behind-the-scenes look at our rigorous cleaning and service schedule. Why our rentals feel brand new every time.",
                content: `
# The White Glove Standard

We don't just rent cars; we curate experiences. And nothing ruins an experience faster than a dirty or poorly maintained vehicle. At **SlingMe**, we are obsessive about maintenance.

## The Turnaround Process
When a vehicle returns, it doesn't just get a hose down.
1.  **Mechanical Check:** Tires, brakes, fluids, and belt tension are inspected by our certified tech.
2.  **Detailing:** The interior is vacuumed and sanitized. The exterior is hand-washed and spray-waxed to maintain that showroom shine.
3.  **Touchpoints:** Steering wheel, shifter, and screens are disinfected.

## Preventative Care
We follow a strict service schedule that exceeds the manufacturer's recommendations. Oil changes, tire rotations, and alignments are done early and often. We want you to feel confident pushing the vehicle, knowing it's in peak condition.
          `,
                image_url: "/article_maintenance_shop.png",
                author: "Head Mechanic",
                is_published: true,
                published_at: Date.now() - 777600000,
            }
        ];

        for (const article of articles) {
            await ctx.db.insert("articles", article);
        }
    },
});
